import React, { useState } from "react";
import { 
  ChevronDown, ChevronUp, HelpCircle, 
  ShieldCheck, AlertTriangle, Search, Info 
} from "lucide-react";

const FAQPage = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedIndex, setExpandedIndex] = useState(null);

  const faqs = [
    {
      category: "General",
      question: "What is FAEAS?",
      answer: "FAEAS (Flood and Earthquake Alert System) is a community safety platform designed to bridge technical disaster data with real-time community safety alerts. It provides instant, verified first-aid workflows and critical disaster instructions during emergency situations."
    },
    {
      category: "Data & Accuracy",
      question: "How are disaster reports and emergency instructions verified?",
      answer: "Unlike platforms that rely on experimental AI or unverified crowd sourcing, FAEAS utilizes a strict, rule-based validation system to audit disaster reports. Every first-aid instruction and rescue protocol available in our database is pre-verified against certified medical and disaster-response standards."
    },
    {
      category: "Usage",
      question: "How does the Rescue Search feature work?",
      answer: "Our search tool operates like an intelligent emergency index. When you type an injury, symptom, or situation (e.g., 'broken bone' or 'water'), the system cleans out conversational stop words, runs a synonym expansion, and matches your text against weighted database keywords. It then returns the most relevant guides ranked by relevance score."
    },
    {
      category: "Validation Engine",
      question: "What rules dictate a report's confidence score?",
      answer: "For environmental disasters like floods, our backend validation rules engine computes weights dynamically: 50% is allocated to immediate live weather API precipitation matching records, 25% is granted if matching social proof reports are active nearby within a spatial radius, and 25% is generated by community consensus citizen upvotes."
    },
    {
      category: "Chatbot Backend",
      question: "How does the Precautionary Chatbot select safety tips?",
      answer: "The safety chatbot runs a predictable keyword intersection density tracking algorithm on your query instead of using conversational large language models. It decomposes your prompt into clean, lowercase words, intersects them against predefined safety keyword rows in our database, and returns completely reliable, hallucination-free care advice."
    },
    {
      category: "NGO Logistics",
      question: "How does the platform track NGO dispatch fulfillment?",
      answer: "To preserve strict inventory auditing, our platform uses atomic database transactions to track relief supply flows. When an NGO dispatches items to a disaster area, the system confirms warehouse balance limits, deducts the stock, and writes a permanent ledger record inside our dispatch log registry to prevent data inflation errors."
    },
    {
      category: "Community Trust",
      question: "What is the purpose of the upvote and downvote metrics?",
      answer: "Community voting establishes real-time crowd-sourced verification weights. If an initial report fails automatic hardware or API tracking parameters, citizen votes bridge the gap. An upvote pushes an unverified report past our validation engine threshold, while downvotes help flag duplicate or fraudulent alerts."
    },
    {
      category: "Emergency",
      question: "Can I use this app as a replacement for emergency services?",
      answer: "No. FAEAS is designed to provide immediate, actionable first-aid instructions while help is on the way. In any critical or life-threatening situation, your absolute priority should always be to contact local emergency services immediately by dialing 1122."
    },
    {
      category: "Technical",
      question: "What should I do if my search query doesn't return a direct match?",
      answer: "If the confidence rating for a query falls below our safety threshold (25%), the system refutes the match to prevent showing dangerous or unrelated advice. Instead, it displays a fallback message guiding you to immediately contact professional rescue teams."
    }
  ];

  const toggleExpand = (index) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  // Filter FAQs based on search input across question, answer, and category parameters
  const filteredFaqs = faqs.filter(
    (faq) =>
      faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.answer.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.category.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center p-4 sm:p-12 font-sans">
      
      {/* FAQ HEADER */}
      <div className="max-w-3xl w-full text-center space-y-6 mt-6 mb-10">
        <div className="flex items-center justify-center gap-3">
          <div className="bg-indigo-100 w-12 h-12 rounded-xl flex items-center justify-center">
            <HelpCircle className="text-indigo-600" size={24} />
          </div>
          <h1 className="text-3xl font-black text-gray-900 tracking-tight">Frequently Asked Questions</h1>
        </div>

      </div>

      {/* --- FAQ ACCORDION LIST --- */}
      <div className="max-w-2xl w-full space-y-4">
        {filteredFaqs.length === 0 ? (
          <div className="bg-white rounded-2xl border border-gray-200 p-8 text-center text-gray-500">
            <Info className="mx-auto mb-2 text-gray-400" size={24} />
            <p className="font-medium">No FAQs found matching your keywords.</p>
          </div>
        ) : (
          filteredFaqs.map((faq, index) => {
            const isExpanded = expandedIndex === index;

            return (
              <div 
                key={index}
                className={`bg-white rounded-2xl border transition-all duration-200 overflow-hidden ${
                  isExpanded 
                    ? "border-indigo-300 ring-4 ring-indigo-500/5 shadow-md" 
                    : "border-gray-200 hover:border-gray-300"
                }`}
              >
                {/* Accordion Header Row */}
                <div 
                  onClick={() => toggleExpand(index)}
                  className="p-5 flex items-center justify-between gap-4 cursor-pointer select-none hover:bg-gray-50/50 transition-colors"
                >
                  <div className="space-y-1 flex-1">
                    <span className="text-[10px] font-black tracking-widest text-indigo-500 uppercase">
                      {faq.category}
                    </span>
                    <h3 className="text-base font-bold text-gray-900 tracking-tight">
                      {faq.question}
                    </h3>
                  </div>

                  <div className="text-gray-400 shrink-0">
                    {isExpanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                  </div>
                </div>

                {/* Dropdown Content Row */}
                {isExpanded && (
                  <div className="px-5 pb-5 border-t border-gray-100 bg-white pt-4 animate-in fade-in duration-200">
                    <p className="text-gray-600 text-sm leading-relaxed font-medium">
                      {faq.answer}
                    </p>
                    
                    {/* Specialized contextual warnings for the Emergency FAQ entry */}
                    {faq.category === "Emergency" && (
                      <div className="mt-4 bg-red-50 p-4 rounded-xl border border-red-100 flex items-start gap-3">
                        <AlertTriangle className="text-red-600 shrink-0 mt-0.5" size={16} />
                        <p className="text-xs text-red-800 font-semibold leading-relaxed">
                          CRITICAL REMINDER: Always secure physical safety first. Do not compromise execution safety by delaying contact with 1122 medical services.
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

    </div>
  );
};

export default FAQPage;